### ISSUE TITLE
Understand the output of ucd.utils.read_results

### ISSUE THREAD

**Issue by bitona** [dchary/ucdeconvolve#7]
Hello,

thanks for a great tool!

I am trying tounderstand how to process the output of `ucd.tl.base(adata)` for a bulk RNA-Seq dataset.
what are the scores contained in `preds = ucd.utils.read_results(adata)`? 
How to extract what is the actual prediction for cell type fractions for each sample from `preds`?

**Comment by dchary** [comment]
Hi @bitona, thanks for reaching out! By default UCDBase will return prediction results back into the input anndata object under the `obsm` dictionary. The results are stored as a 2D array with the rows being samples and the columns being the cell types. The values are the predicted fraction of the given cell type for that sample. We store the array and the column name headers separately, and the function `ucd.utils.read_results(adata)` just extracts the array and header and merges them into a pandas dataframe which is then returned as `preds`. The row indices for the returned `preds` dataframe will be the same as the sample names / indices in the underlying anndata object (which can be viewed in `adata.obs_names`).  They should also be in the same order. 

To extract a prediction for a given celltype, you can index the dataframe by doing `preds["t cell"]` which would return a 1-D pandas series containing t cell predictions for all your samples. Conversely if you are interested in the predictions for a specific sample you can index the dataframe by row by doing `preds.loc["sample_name"]` or for multiple samples `preds.loc[["sample1", "sample2"]]`. You can of course combine these two operations to get both sample and cell-type subsets. 

For more information on the data strutures used with UCD, I would highly recommend the documentation provided by the developers of the `anndata` and `pandas` packages, which can be found [here](https://anndata.readthedocs.io/en/latest/index.html) and [here](https://pandas.pydata.org/docs/), respectively. Let me know if you have any additional questions!
